### PR TITLE
B#74 ethercat grant

### LINKED ISSUE #74: [ros_ethercat_loop] RPATH issues when using ethercat_grant on bionic
the bug is related to  https://github.com/shadow-robot/ethercat_grant/issues/4 when one starts the driver on bionic, some libs are not found through the RUNPATH.

```
process[sr_hand_robot-3]: started with pid [256937]
catkin_ws_shadow/devel/lib/ros_ethercat_loop/ros_ethercat_loop: error while loading shared libraries: librosconsole_bridge.so: cannot open shared object file: No such file or directory
[sr_hand_robot-3] process has died [pid 256937, exit code 127, cmd ethercat_grant catkin_ws_shadow/devel/lib/ros_ethercat_loop/ros_ethercat_loop -i ethercat2 -r robot_description __name:=sr_hand_robot 

```
to fix this issue one can add the linker flag  ```--disable-new-dtags```  to use the old RPATH but the problem is explicitly a dependency of dependency (rosconsole_bridge is a dependency of liburdfdom which itself does not have use RPATH) 

```
LD_DEBUG=files ldd catkin_ws_shadow/devel/lib/ros_ethercat_loop/ros_ethercat_loop 
 266364:	file=librosconsole_bridge.so [0];  needed by /opt/ros/melodic/lib/liburdf.so [0]
```

so the trick is to explicitly request ros_ethercat_loop to use librosconsole_bridge itself and then find it via its own RPATH

a PR with these two patches will be provided

### PR DESCRIPTION
**Pull request by guihomework**
fixes #74 via 2 commits, both needed. A third commit is needed to compile ans is available there #75. When #75 is merged, I can rebase this PR if you like a clean merge.

### CODE REVIEW

**Comment by AndriyPt** [comment]
@guihomework please rebase PR for clean merge since #75 was merged.

**Comment by guihomework** [comment]
Rebased, and I also double checked that it is compatible with kinetic. It compiles and runs (not tested on a real hand, but the ethercat loop starts and finds all dependencies). 
This change is needed for bionic and was tested on a real hand there

**Comment by AndriyPt** [comment]
@guihomework thank you for rebase.
Please add `rosconsole_bridge` dependency to `package.xml` and `CMakeLists.txt`

**Comment by guihomework** [comment]
indeed. done

**Review by AndriyPt — APPROVED** [review]

**Pull request merged**
