### PR TITLE
updating switchcontrollers

### PR DESCRIPTION
**Pull request by biofotis**
## Proposed changes

fixing the error for the new message for melodic

## Types of changes

What types of changes does your code introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

Put an x in the boxes that apply. You can also fill these out after creating the PR. This is a reminder of what we should look for before merging this code. I have:

- [ ] Read and follow the [contributing guidelines](https://github.com/shadow-robot/sr_documentation/blob/master/CONTRIBUTING.md).
- [x] Checked that all tests pass with my changes
- [ ] Added tests (automatic or manual) that prove the fix is effective or that the feature works
- [ ] Added necessary documentation (if appropriate)
- [ ] Added the corresponding license to each file and add the current year of any one that you modified.
- [x] Tested on real hardware (if appropriate)

### CODE REVIEW

**Review by beatrizleon — APPROVED** [review]

**Comment by guihomework** [comment]
this fix will break again next time a message change occurs. Why not instantiate a SwitchControllerRequest which would have any new field already setup to default values.

**Comment by biofotis** [comment]
Yes we can do that as well. I wasn't so sure about the defaults values as they might didnt work well with hardware. I confirm they do after testing it. Please feel free to update it with a PR

**Comment by guihomework** [comment]
So you mean that it would actually be a "safety" feature to still call with given fixed set of parameters, and in case parameters are added, it will break and then somebody will look at it, whereas with my idea, default values might break things and/or get unnoticed.

I think your way is still risky because if parameters change "order" (maybe never happens) the call might send wrong values to wrong parameters and also be unnoticed.

I will provide a PR and you will decide to merge it or not.

**Comment by guihomework** [comment]
done here https://github.com/shadow-robot/ros_ethercat/pull/97

**Pull request merged**
